# Generated by Django 3.0b1 on 2019-10-26 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_phone', models.CharField(max_length=14)),
                ('user_email', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=30)),
                ('pub_date', models.DateField(verbose_name=datetime.datetime(2019, 10, 26, 20, 57, 26, 885217))),
            ],
        ),
    ]
