# Generated by Django 3.0b1 on 2019-10-26 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 21, 12, 47, 376769)),
        ),
    ]
