# Generated by Django 3.0b1 on 2019-10-26 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_auto_20191026_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 21, 20, 28, 162001)),
        ),
    ]
