# Generated by Django 3.0b1 on 2019-10-27 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20191026_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 13, 0, 40, 457929)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
