# Generated by Django 3.0b1 on 2019-10-27 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20191027_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 13, 6, 33, 379915)),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_phone',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
